### PR TITLE
Use alias for brevity

### PR DESCRIPTION
**Pull request by mejai1206**
## 🙏 Describe the pull request
triton.language 를 tl로 변경하였습니다.

## ✅ Checklist
- [x] Code follows the project's coding conventions and style.
- [x] Tests have been added or updated to cover the changes.
- [x] Documentation has been updated, if necessary.

### CODE REVIEW

**Review by kakao-steve-ai — APPROVED** [review]
LGTM

**Review by daemyung — CHANGES_REQUESTED** [review]
커밋 메세지를 다음과 같이 제안드립니다.

```
Use alias for brevity

triton.language is replaced with tl.
```

**Comment by mejai1206** [comment]
커밋 메세지

Use alias for brevity

triton.language is replaced with tl

수정하였습니다.

**Review by daemyung — APPROVED** [review]
LGTM

**Pull request merged**
