### PR TITLE
Release Trident 0.1.1

### PR DESCRIPTION
**Pull request by kakao-steve-ai**
## 🙏 Describe the pull request

Release Version 0.1.1 

## ✅ Checklist

- [x] Code follows the project's coding conventions and style.
- [x] Tests have been added or updated to cover the changes.
- [x] Documentation has been updated, if necessary.

### CODE REVIEW

**Review by mejai1206 — APPROVED** [review]
LGTM

**Review by daemyung — CHANGES_REQUESTED** [review]
`Release Trident 0.1.1` 제목 어떠세요? Trident를 빼거나?

**Comment by kakao-steve-ai** [comment]
> `Release Trident 0.1.1` 제목 어떠세요? Trident를 빼거나?

`Release Trident 0.1.1`로 수정하였습니다.

**Review by daemyung — CHANGES_REQUESTED** [review]
LGTM

**Review by daemyung — APPROVED** [review]
LGTM

**Pull request merged**
